["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "./lib"

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src", "./lib/cairo_math_64x61/contracts"]
stdout-on-success = true

# This section is explained in the "Project compilation" guide.
["protostar.contracts"]
main = ["./contracts/settling_game/Arbiter.cairo"]

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.test"]
disable-hint-validation = true
